include:
  - local: .gitlab/defaults.yml

stages:
  - build
  - deploy
  - lint
  - test
  - scan
  - coverage
  - archive
  - sync

deploy DSS:
  stage: deploy
  variables:
    BRANCH_NAME: $BRANCH_NAME
    UPSTREAM_REF: $CI_MERGE_REQUEST_REF_PATH
  trigger:
    include:
      project: dfs/dss/dss-ansible
      ref: master
      file: .gitlab-ci.yml
    strategy: depend
  resource_group: inv_$CI_PROJECT_NAME.ini
  rules:
    - !reference [.default_rules, merge_and_push]
