---

- name: Make sure to empty the destination location
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ dfly_temp_dir }}"
    - "{{ temp_dir }}/{{ image_name }}.tar"

- name: Find target RPMs
  find:
    path: "{{ playbook_dir }}/release/"
    patterns: >-
      '{% for package in target_packages}{{ package }}*.rpm{% if not loop.last %},{% endif %}{% endfor %}'
  delegate_to: localhost
  run_once: true
  register: found_target_packages

- name: Assert target packages found
  assert:
    that: found_target_packages.files | length == target_packages | length
    fail_msg: Target packages not found. Build target and agent packages first.

- name: Create RPM staging directory
  file:
    state: directory
    path: '{{ dfly_temp_dir }}'
    mode: 0755
  become: yes

- name: Copy target RPMs
  copy:
    src: "{{ item.path }}"
    dest: "{{ dfly_temp_dir }}"
  loop: "{{ found_target_packages.files }}"
  loop_control:
    label: "{{ item.path }}"
