---

- name: Copy python script to remote location
  template:
    src: install_packages.py
    dest: /tmp/install_packages.py

- name: Install required Target packages using script
  shell: python /tmp/install_packages.py "{{ target_packages }}"
  register: install_log

- name: Print install log
  debug:
    msg: "{{ install_log.stdout }}"
