---
- name: Set PATH & PYTHONPATH in .bashrc
  shell: echo export {{ item }} >> ~/.bashrc
  with_items:
    - "PYTHONPATH={{ cm_dir }}:$PYTHONPATH"
    - "PATH={{ product_dir }}:{{ ansible_env.PATH }}"
    - ETCDCTL_API=3

