#!/usr/bin/env bash
#
#
echo "Now running post un-installer!"

die()
{
    echo "$*"
    exit 1
}

SERVICE="ufm_msg_broker"
APP_PATH="/usr/share/ufmbroker"
SERVICE_PATH="/usr/share/ufmbroker/systemd"

# if update do not remove anything
[[ $1 -eq 1 ]] && exit 0
[[ "$1" == "upgrade" ]] && exit 0

if [[ -e /etc/systemd/system/${SERVICE}.service ]]
then
    systemctl disable ${SERVICE}
    systemctl stop ${SERVICE}
    rm /etc/systemd/system/${SERVICE}.service
fi

if [[ -e ${APP_PATH} ]]
then
    rm -rf ${APP_PATH}
fi

if [[ -e /var/log/ufm_msg_broker ]]
then
    rm -rf /var/log/ufm_msg_broker
fi

exit 0

