#!/usr/bin/env bash
#
#
echo "Now running pre-installer!"

if [[ ! -x /usr/bin/python3 ]]
then
    echo "ERR: Python3 is not installed"
    exit 1
fi

/usr/bin/env python3 -m pip install pyzmq

exit 0

