version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    DSSGLOBLIST: "nkv-sdk-*.tgz nkv-target-*.tgz ufm-*.rpm ufmbroker-*.rpm nkvagent-*.rpm"

phases:
  build:
    commands:
      - |
        build-wrapper-linux-x86-64 --out-dir bw-output \
          ./scripts/build_all.sh kdd-samsung-remote
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "$GITHUB_REF_NAME")" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.pullrequest.github.summary_comment=true \
          -Dsonar.pullrequest.provider=GitHub \
          -Dsonar.pullrequest.github.repository=OpenMPDK/dss-sdk \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=$GITHUB_BASE_REF \
          -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF
  post_build:
    commands:
      - /stagemergeartifacts.sh

artifacts:
  files:
    - df_out/nkv-target-*.tgz
    - host_out/nkv-sdk-bin-*.tgz
    - ufm/agents/nkv_agent/nkvagent-*.rpm
    - ufm/fabricmanager/ufm-*.rpm
    - ufm/ufm_ufm_msg_broker/ufmbroker-*.rpm
  discard-paths: yes
  name: builds/dss-sdk/$CODEBUILD_BUILD_NUMBER
