version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    SONAR_UNIT_TEST_REPORT: df_out/reports/sonar_qube_ut_coverage_report.xml

phases:
  pre_build:
    commands:
      # Download build wrapper output from build job
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/sonar" . --only-show-errors
      # Download df_out and host_out
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/build" . --only-show-errors
      # Download unit test coverage report(s)
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/unit/df_out/reports/" df_out/ --only-show-errors
      # Correct paths of target files in coverage report
      - sed -i -r 's/path="/path="target\//g' $SONAR_UNIT_TEST_REPORT
      # replace the old CODEBUILD_SRC_DIR with the current one in bw-output
      - sed -i -r "s|/codebuild/output/src[^/]+/src/github.com/OpenMPDK/dss-ecosystem|$CODEBUILD_SRC_DIR|g" bw-output/build-wrapper-dump.json
  build:
    commands:
      # Run sonar-scanner and ingest coverage report(s)
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "$GITHUB_REF_NAME")" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.pullrequest.github.summary_comment=true \
          -Dsonar.pullrequest.provider=GitHub \
          -Dsonar.pullrequest.github.repository=OpenMPDK/dss-sdk \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=$GITHUB_BASE_REF \
          -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF \
          -Dsonar.python.coverage.reportPaths=$SONAR_UNIT_TEST_REPORT
