version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    DSSGLOBLIST: "nkv-sdk-*.tgz nkv-target-*.tgz"

phases:
  build:
    commands:
      # Download build wrapper output from dss-client build job
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/sonar" . --only-show-errors
      # Download unit test coverage report(s)
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/unit/df_out/reports/" df_out/ --only-show-errors
      # Download df_out and host_out
      - aws s3 cp --recursive "$DSSS3URI/cache/dss-sdk/$GITHUB_RUN_NUMBER/build" . --only-show-errors
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "$GITHUB_REF_NAME")" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.pullrequest.github.summary_comment=true \
          -Dsonar.pullrequest.provider=GitHub \
          -Dsonar.pullrequest.github.repository=OpenMPDK/dss-sdk \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=$GITHUB_BASE_REF \
          -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF
  post_build:
    commands:
      - /stagemergeartifacts.sh

artifacts:
  files:
    - df_out/nkv-target-*.tgz
    - host_out/nkv-sdk-bin-*.tgz
  discard-paths: yes
  name: builds/dss-sdk/$CODEBUILD_BUILD_NUMBER
