#!/bin/bash
git_hash=$(git describe --abbrev=4 --always --tags)
echo "/* Do not edit this file directly, it is autogenerated during build */" > src/include_private/dss_version.h
echo "" >> src/include_private/dss_version.h
echo "" >> src/include_private/dss_version.h
echo "#ifndef GITHASH_H" >> src/include_private/dss_version.h
echo "#define GITHASH_H" >> src/include_private/dss_version.h
echo "const std::string dssVersion = \"$git_hash\";" >> src/include_private/dss_version.h
echo "#endif // GITHASH_H" >> src/include_private/dss_version.h
