
SERVER_ATTRIBUTES_NAME = 'server_attributes'
SERVER_ATTRIBUTES = '%s/' % SERVER_ATTRIBUTES_NAME
SERVER_ATTRIBUTES_METADATA = SERVER_ATTRIBUTES + 'metadata/'

KV_ATTRIBUTES_NAME = 'kv_attributes'
KV_ATTRIBUTES = '%s/' % KV_ATTRIBUTES_NAME
KV_ATTRIBUTES_CONFIG = KV_ATTRIBUTES + 'config/'
KV_ATTRIBUTES_SUBSYSTEMS = KV_ATTRIBUTES_CONFIG + 'subsystems/'

SERVER_LIST_NAME = 'list'
SERVER_LIST = '%s/' % SERVER_LIST_NAME
