---

# Failover related stuff
cluster_failover_ip: 10.1.30.245
etcd_cluster_name: dummy_cluster

# NTP Server
ntp_server: 0.us.pool.ntp.org

# Stats Server
# Graphite server
stats_proto: graphite
stats_ip: 0.0.0.0
stats_port: 2004

# StatsD server
#stats_proto: statsd
#stats_ip: 0.0.0.0
#stats_port: 8125
