---

- name: create etcd group
  become: yes
  become_user: root
  group:
    name: '{{ etcd_group }}'
    state: present

- name: create etcd user
  become: yes
  become_user: root
  user:
    name: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    home: '{{ etcd_data_dir }}'
    state: present

- name: create dirs...
  become: yes
  become_user: root
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0755
  with_items:
    - /etc/etcd
    - "{{ etcd_data_dir }}"

- include_tasks: pki.yml
  when: etcd_secure

- include_tasks: systemd.yml
