---

- name: Get kernel
  command: uname -r
  changed_when: false
  register: kernel_ver

- name: Assert valid kernel version
  assert:
    that: kernel_ver.stdout in kernel_devel_url
    msg: |
      Found kernel version {{ kernel_ver.stdout }}
      Required kernel must match {{ kernel_devel_url }}

- name: Install yum dependencies
  yum:
    name:
      - bison
      - cmake
      - flex
      - gcc
      - gcc-c++
      - git
      - libaio-devel
      - libuuid-devel
      - numactl-devel
      - openssl-devel
      - rdma-core-devel
      - rpm-build
      - tbb-devel
      - "{{ kernel_devel_url }}"
    state: present
  become: yes
