---

- name: Make sure Chrony is started up
  service:
    name: chronyd
    state: started
    enabled: yes

- name: set timezone
  timezone:
    name: America/Los_Angeles

- name: Copy over the NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd

- name: Make sure NTP is stopped
  service:
    name: ntpd
    state: stopped
    enabled: yes

- name: Sync time initialy
  command: "ntpdate {{ ntp_server }}"

- name: Make sure NTP is started up
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Sync hwclock
  command: hwclock -w
