---

- name: Install the latest version of epel-release
  yum:
    name: epel-release
    enablerepo: extras
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Debian dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ debian_package_dependencies }}"
  when: ansible_os_family == 'Debian'
  ignore_errors: true

- name: Install FM RHEL dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ fm_rhel_package_dependencies }}"
  when: ansible_os_family == 'RedHat' and inventory_hostname in groups['fm_hosts']

- name: Install Target RHEL dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ target_rhel_package_dependencies }}"
  when: ansible_os_family == 'RedHat' and inventory_hostname in groups['targets']

- name: Set selinux to permissive (temp)
  shell: setenforce 0
  ignore_errors: true

- name: Disable SELinux (effective next reboot)
  selinux:
    state: disabled
  ignore_errors: true

- name: Make sure firewall disabled
  become: yes
  become_user: root
  service:
    name: firewalld
    enabled: no
    state: stopped

#- name: Add ports to firewalld
#  firewalld:
#    port: "{{ item }}"
#    permanent: true
#    state: enabled
#  with_items:
#    - 2379-2380/tcp
#    - 8080/tcp

#- name: Reload firewalld
#  shell: firewall-cmd --reload

#- name: Copy etcd/etcdctl to machines
#  copy:
#    src: "{{ item }}"
#    dest: "/usr/bin/"
#    mode: 0755
#  with_items:
#    - etcd
#    - etcdctl

