---

- name: Install the latest version of epel-release
  yum:
    name: epel-release
    enablerepo: extras
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Debian dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ debian_package_dependencies }}"
  when: ansible_os_family == 'Debian'
  ignore_errors: true

- name: Install FM RHEL dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ fm_rhel_package_dependencies }}"
  when: ansible_os_family == 'RedHat' and inventory_hostname in groups['fm_hosts']

- name: Install Target RHEL dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ target_rhel_package_dependencies }}"
  when: ansible_os_family == 'RedHat' and inventory_hostname in groups['targets']

- name: Get selinux status
  shell: 'sestatus | grep -oP "SELinux status: +\K.+"'
  register: selinux_status
  changed_when: false

- name: Get selinux policy name
  shell: 'sestatus | grep -oP "Loaded policy name: +\K.+"'
  register: selinux_policy
  changed_when: false
  when: selinux_status.stdout == "enabled"

- name: Set selinux to permissive (temp)
  selinux:
    state: permissive
    policy: "{{ selinux_policy.stdout }}"
  when: selinux_status.stdout == "enabled"

- name: Disable SELinux (effective next reboot)
  selinux:
    state: disabled

- name: Make sure firewall disabled
  service:
    name: firewalld
    enabled: no
    state: stopped
