#!/bin/bash
#
#
echo "Now running post installer!"

die()
{
  echo "$*"
  exit 1
}

SERVICE="ufm"
SERVICE_PATH="/usr/share/${SERVICE}/systemd"

if [[ "$1" == "configure" ]]
then
  [[ -e ${SERVICE_PATH}/${SERVICE}.service ]] && systemctl stop ${SERVICE}
fi

# Create directory for log files
# TODO(ER) this should be moved to the UFM and removed from here
if [[ ! -e /var/log/ufm ]]
then
  mkdir -p /var/log/ufm
  chmod 666 /var/log/ufm
fi

# This check should not longer be needed, since
# python3-pip is dependency for this install see control file
#
# command -v pip3 > /dev/null
# [[ $? -ne 0 ]] && die "ERR: pip3 is not installed"

# See https://snarky.ca/why-you-should-use-python-m-pip/
# to know why the safe way to execute pip is python3 -m pip,
# not pip3.
# /usr/bin/env pip3 install -r /usr/share/${SERVICE}/requirements.txt

/usr/bin/env python3 -m pip install -r /usr/share/${SERVICE}/requirements.txt
[[ $? -ne 0 ]] && die "ERR: Failed to install requirements.txt "

[[ ! -e ${SERVICE_PATH}/${SERVICE}.service ]] && die "ERR: Failed to create service file for ${SERVICE}"
[[ ! -e ${SERVICE_PATH}/gunicorn.service ]] && die "ERR: Failed to copy gunicorn service file"

cp ${SERVICE_PATH}/${SERVICE}.service /etc/systemd/system/
cp ${SERVICE_PATH}/gunicorn.service /etc/systemd/system/

systemctl daemon-reload

systemctl enable gunicorn
systemctl start gunicorn

systemctl enable ${SERVICE}
systemctl start ${SERVICE}

exit 0

