#!/usr/bin/env bash
#
#
echo "Now running the pre un-installer!"

SERVICE="ufm"
SERVICE_PATH="/usr/share/${SERVICE}/systemd"

# if update do not remove anything
[[ $1 -eq 1 ]] && exit 0
[[ "$1" == "upgrade" ]] && exit 0


if [[ -e ${SERVICE_PATH}/${SERVICE}.service ]]
then
  systemctl disable ${SERVICE}
  systemctl stop ${SERVICE}
fi

if [[ -e /etc/systemd/system/gunicorn.service ]]
then
  systemctl disable gunicorn
  systemctl stop gunicorn
fi


exit 0

