---

- name: Open etcd ports (ufw)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  when:
    - "'ufw.service' in ansible_facts.services"
    - ansible_facts.services['ufw.service'].state == "running"
  become: yes
  loop:
    - "{{ ufm_redfish_port }}"
    - "{{ ufm_zmq_subscriber_port }}"
