---

- name: Set Leader
  block:
    - name: Init Leader var
      set_fact:
        isLeader: false

    - name: etcdctl find leader
      shell: "etcdctl member list | grep {{ ansible_default_ipv4.address }}"
      register: output
      environment:
        ETCDCTL_API: 2

    - name: Set Leader var
      set_fact:
        isLeader: true
      when: output.stdout.find('isLeader=true') != -1
  when: inventory_hostname in groups['fm_hosts']

- name: Set Variables
  block:
    - name: Set dfly_config var
      set_fact:
        dfly_config: "{{ lookup('file', dfly_file) }}"

    - name: Set dfly vars
      set_fact:
        dfly_groups: "{{ dfly_config | regex_findall('(?<!#)\\[(?!GLOBAL)(.*?)\\]') }}"
        subsystem_ips: "{{ dfly_config | regex_findall('(?<!#)subsystem_ip_port: *([0-9]+.[0-9]+.[0-9]+.[0-9]+):[0-9]+,*') }}"

    - name: Print dfly vars
      debug:
        var: item
      loop:
        - "{{ subsystem_ips }}"
        - "{{ dfly_groups }}"
  run_once: true

- name: Execute event tests
  block:
    - include_tasks: agent_events.yml
    - include_tasks: subsystem_events.yml
    - include_tasks: interface_events.yml
  always:
    - name: Bring up interface that was tested {{ ethtest_interface }}
      command: "ifup {{ ethtest_interface }}"
      when:
        - ethtest_target_node is defined
        - ethtest_interface is defined
        - inventory_hostname == ethtest_target_node

    - name: Start target services on all targets
      service:
        name: "{{ item }}"
        state: started
      loop:
        - nvmf_tgt
        - kv_cli
      when: inventory_hostname in groups['targets']

    - name: Verify target services are running on all targets
      systemd:
        name: "{{ item }}"
      register: service_status
      failed_when: service_status.status.ActiveState != "active"
      loop:
        - nvmf_tgt
        - kv_cli
      when: inventory_hostname in groups['targets']
