- name: confirm whether user really meant to purge the cluster
  hosts: localhost
  gather_facts: true
  vars_files:
    - ./group_vars/all.yml

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to purge the cluster?
      default: 'no'
      private: no

  tasks:
  - name: exit playbook, if user did not mean to purge cluster
    fail:
      msg: >
        "Exiting purge-cluster playbook, cluster was NOT purged.
         To purge the cluster, either say 'yes' on the prompt or
         or use `-e ireallymeanit=yes` on the command line when
         invoking the playbook"
    when: ireallymeanit != 'yes'

- name: Reset fm_hosts
  hosts: fm_hosts
  roles:
    - ufm_reset

- name: Reset targets
  hosts: targets
  gather_facts: false
  roles:
    - tgt_reset
