---

- name: Copy UFM RPMs to CentOS Fabric Manager Hosts
  copy:
    src: "{{ item.stdout }}"
    dest: "{{ ufm_devtest_staging_dir }}"
  loop:
    - "{{ ufm_rpm }}"
    - "{{ ufmbroker_rpm }}"
  loop_control:
    label: "{{ item.stdout }}"

- name: Install UFM RPMs
  yum:
    name: "{{ ufm_devtest_staging_dir }}/{{ item.stdout | basename }}"
  become: yes
  loop:
    - "{{ ufm_rpm }}"
    - "{{ ufmbroker_rpm }}"
  loop_control:
    label: "{{ ufm_devtest_staging_dir }}/{{ item.stdout | basename }}"
