---

- name: Copy DEBs to Ubuntu Fabric Manager Hosts
  copy:
    src: "{{ item.stdout }}"
    dest: "{{ ufm_devtest_staging_dir }}"
  loop:
    - "{{ ufm_deb }}"
    - "{{ ufmbroker_deb }}"
  loop_control:
    label: "{{ item.stdout }}"

- name: Install Dev DEBs
  apt:
    deb: "{{ ufm_devtest_staging_dir }}/{{ item.stdout | basename }}"
  become: yes
  loop:
    - "{{ ufm_deb }}"
    - "{{ ufmbroker_deb }}"
  loop_control:
    label: "{{ ufm_devtest_staging_dir }}/{{ item.stdout | basename }}"
