---

- name: Copy UFM RPMs to CentOS Fabric Manager Hosts
  copy:
    src: "{{ item }}"
    dest: "{{ ufm_devtest_staging_dir }}"
  loop:
    - "{{ ufm_rpm.files[0].path }}"
    - "{{ ufmbroker_rpm.files[0].path }}"
  loop_control:
    label: "{{ item }}"

- name: Install UFM RPMs
  yum:
    name: "{{ ufm_devtest_staging_dir }}/{{ item | basename }}"
  register: ufm_rpm_status
  become: yes
  loop:
    - "{{ ufm_rpm.files[0].path }}"
    - "{{ ufmbroker_rpm.files[0].path }}"
  loop_control:
    label: "{{ ufm_devtest_staging_dir }}/{{ item | basename }}"
  failed_when: "'scriptlet failure' in ufm_rpm_status.msg"
