---

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  become: yes

- name: Install yum dependencies
  yum:
    name:
      - epel-release
      - ruby-devel
      - dpkg
    state: present
  become: yes

- name: Install fpm gem
  gem:
    name: fpm
    state: present
    user_install: no
  become: yes
