---

- name: Open etcd ports (firewalld)
  firewalld:
    port: "{{ item }}/tcp"
    immediate: true
    permanent: yes
    state: enabled
  when:
    - "'firewalld.service' in ansible_facts.services"
    - ansible_facts.services['firewalld.service'].state == "running"
  become: yes
  loop:
    - "{{ ufm_etcd_client_port }}"
    - "{{ ufm_etcd_peer_port }}"
    - "{{ ufm_redfish_port }}"
    - "{{ ufm_haproxy_health_port }}"
    - "{{ ufm_zmq_subscriber_port }}"
    - "{{ ufm_zmq_subscriber_port }}"
