---
# Main Tasks for Phoenix FabricManager Build Environment

- name: Install Dependencies (apt)
  apt:
    name:
      - ruby-dev
      - build-essential
      - rpm
  become: yes

- name: Install FPM (gem)
  gem:
    name: fpm
    state: present
  become: yes
