---

- name: create dirs...
  become: yes
  become_user: root
  file:
    state: directory
    path: '{{ item }}'
    mode: 0755
  with_items:
    - "{{ config_file_dir }}"
    - "{{ nkv_agent_config_file_dir }}"
    - "{{ logfile_dir }}"

- name: Copy agent configuration file
  template:
    src: agent.conf.j2
    dest: "{{ item }}/agent.conf"
    mode: 0755
  loop:
    - "{{ config_file_dir }}"
    - "{{ nkv_agent_config_file_dir }}"

- name: Copy dragonfly_config file to remote host
  copy:
    src: "{{ playbook_dir }}/DFLY_CONFIG"
    dest: "{{ config_file_dir }}"
