JSONRPC_RECV_PACKET_SIZE = 4096
DEFAULT_SPDK_SOCKET_PATH = "/var/run/spdk.sock"
SPDK_CONF_NUM_OF_MD_PARAMS = 6
SPDK_RESET = False  # Upon removal and failure reset the device to nvme driver
NVMF_CONF_HEADER = ("# AUTO-GENERATED FILE - DO NOT EDIT\n"
                    "[Global]\n"
                    "LogFacility \"local7\"\n"
                    "\n"
                    "[Nvmf]\n"
                    "AcceptorCore 25\n"
                    "AcceptorPollRate 10\n"
                    "\n"
                    "[DFLY]\n"
                    "KV_PoolEnabled Yes\n"
                    "QoS            No\n"
                    "Qos_host       default_host            \"R:10K L:100M P:50\"\n"
                    "Qos_host       2014-08.org.nvmexpress  \"R:10K L:100M P:50\"\n"
                    "\n"
                    "fuse_enabled No\n"
                    "fuse_nr_maps_per_pool 4\n"
                    "fuse_nr_cores   4\n"
                    "fuse_debug_level 0\n"
                    "fuse_timeout_ms 0\n"
                    "\n"
                    "[Transport1]\n"
                    "Type TCP\n"
                    "MaxQueuesPerSession 64\n"
                    "MaxIOSize 2097152\n"
                    "IOUnitSize 2097152\n"
                    "\n"
                    "#[Transport2]\n"
                    "#Type RDMA\n"
                    "#MaxQueuesPerSession 64\n"
                    "#MaxIOSize 2097152\n"
                    "#IOUnitSize 2097152\n"
                    "\n")
