#!/usr/bin/env bash
#
#
echo "Now running post installer!"

die()
{
    echo "Post install failed"
    echo "$*"
    exit 1
}

SERVICES="kv_cli nvmf_tgt nvmf_tgt@"
SERVICE_PATH="/usr/share/nkvagent/systemd"

if [[ "$1" == "configure" ]]
then
    for s in ${SERVICES}
    do
        [[ -e ${SERVICE_PATH}/${s}.service ]] && systemctl stop ${s}
    done
fi

# Create directory for log files
# TODO(ER) this should be moved to the main()
if [[ ! -e /var/log/nkv-agent ]]
then
    mkdir -p /var/log/nkv-agent
    chmod 666 /var/log/nkv-agent
fi

# for s in ${SERVICES}
# do
#    [[ ! -e ${SERVICE_PATH}/${s}.service ]] && die "ERR: Failed to find service file for ${s}.service"
# done

cp ${SERVICE_PATH}/* /etc/systemd/system/

for s in ${SERVICES}
do
    echo "Enable and start ${s} service "
    systemctl enable ${s}
    systemctl start ${s}
done

exit 0

