#!/usr/bin/env bash
#
#
echo "Now running pre-installer!"

die()
{
    echo "Pre-install failed"
    echo "$*"
    exit 1
}

if [[ ! -x /usr/bin/python ]]
then
    echo "ERR: Python is not installed"
    exit 1
fi

python -m pip install --upgrade pip

# pip psutil install does not work on python2.7 on Centos
# yum install python-psutil

for p in docopt netifaces etcd3 pyinstaller pyzmq
do
    /usr/bin/env python -m pip install ${p} || die "ERR: Failed to install ${p}"
done

exit 0

