#!/usr/bin/env bash
#
#
echo "Running pre-installer!"

die()
{
    echo "Pre-install failed"
    echo "$*"
    exit 1
}

[[ -x "/usr/bin/python" ]] || die "ERR: Python is not installed"

echo "Pre-install done"

