name: dss-sdk
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        component:
          - dss-sdk-build
          - dss-sdk-unit-test
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: ${{ matrix.component }}
      project-name: OpenMPDK_dss-sdk
      compute-type-override: BUILD_GENERAL1_LARGE
    secrets: inherit
  lint:
    strategy:
      matrix:
        component:
          - pycodestyle
          - shellcheck
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: ${{ matrix.component }}
      project-name: OpenMPDK_dss-sdk
    secrets: inherit
  scan:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: sonar-scanner
      project-name: OpenMPDK_dss-sdk
    secrets: inherit
    needs: [build]
