name: dss-sdk
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ansible-lint:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: dss-sdk
      project-name: OpenMPDK_dss-sdk
    secrets: inherit
